spring:
  application:
    name: caovan
    
  #配置数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=utf-8&characterSetResults=utf-8&useUnicode=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  
  jpa:
    show-sql: true

  #配置thymeleaf模板
  thymeleaf:
    prefix: classpath:/templates/ 
    suffix: .html
    cache: false
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    
server:
  port: 80
  tomcat:
    accesslog:
      enabled: true
    basedir: target/tomcat 
         
   
    